# ==============================
# Etapa 1 - Build com Maven
# ==============================
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copia os arquivos do projeto para dentro da imagem
COPY . .

# Faz o build (gera o .jar na pasta target)
RUN mvn -f app-vendas/pom.xml clean package -DskipTests

# ==============================
# Etapa 2 - Runtime (somente JAR final)
# ==============================
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copia apenas o JAR gerado no build
COPY --from=build /app/app-vendas/target/*.jar app.jar

# Expõe a porta padrão do Spring Boot
EXPOSE 8080

# Comando de inicialização
ENTRYPOINT ["java", "-jar", "app.jar"]
